version: "3.7"

services:
  api2:
    image: api2
    build:
      context: ../api2
      dockerfile: Dockerfile.2
    ports:
      - "4200:4200"
  api1:
    image: api1
    build:
      context: ../api1
      dockerfile: Dockerfile
    ports:
      - "4100:4100"
